### ISSUE TITLE
Dashlet content not appearing

### ISSUE THREAD

**Issue by bhahumanists** [TechToThePeople/civisualize#67] opened 2015-07-21 13:39 UTC
Does the dashlet code work ok in 4.5.x? I can see the dashlets, but they don't load any content.

I can see they're trying to grab content from a snippet, but if I access the snippet directly I can see it doesn't have the includes for d3.js etc. so it throws a js error. Could this be stopping the content loading? Or is this perfectly normal?

**Comment by siddharthg** [comment] 2015-07-21 16:21
I can run in it on my instance on 4.5, can you please specify what cms are you using? Is the path to the js folder correct?

**Comment by awestbha** [comment] 2015-07-21 16:30
I'm on WordPress. The visualisations themselves work fine when accessed the usual way - it's just the dashlet. js folder path is fine as far as I know - where would I double-check?

**Comment by tttp** [comment] 2015-07-21 20:27
if everything goes according to the plan, the d3 and other needed javascript are loaded from the main dashboard page, so normal it isn't on each dashlet.

could you check if it's the case or if you can see any error on your console?

**Comment by awestbha** [comment] 2015-07-22 13:41
Got this working, but only with a hack. There were a couple of WordPress-specific problems.

1. To get the .js files to load on the dashboard, the function in visualize.php needs to be civisualize_civicrm_dashboard, rather than civicrm_civicrm_dashboard

2. In dashlet.mgd.php the URL is created using CRM_Utils_System::url(). In WordPress this always seems to produce '/wp-admin/admin.php?page=CiviCRM&q=civicrm/dataviz/whatever&snippet=4'. But the dashlet code is expecting 'civicrm/dataviz/whatever&snippet=4', which I assume is what it gets in Drupal. 

I played around with the parameters of CRM_Utils_System::url() but I couldn't get it to output the right thing. So my hacky fix was to change the url in dashlet.mgd.php to just directly be 'civicrm/dataviz/contacts?snippet=4', and not use CRM_Utils_System::url() at all. This works, but it seems a bit dubious.

**Comment by siddharthg** [comment] 2015-07-23 06:42
Can you send a pull request as well, I would make a wp branch for the same.

**Comment by awestbha** [comment] 2015-07-24 13:46
Although the content appears in the dashlet ok first of all, it seems to have problems when it gets cached. I'll look into that when I can and do a PR if it's fixable.

**Comment by tttp** [comment] 2015-09-01 11:02
duplicate of #48 ?

**Closed** 2020-06-17 08:35 UTC
